# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-02-03 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='返回信息主键')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='数据返回时间')),
                ('voltage', models.CharField(max_length=20, verbose_name='设备电压')),
                ('temperature', models.CharField(max_length=20, verbose_name='温度')),
            ],
        ),
        migrations.CreateModel(
            name='equipment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='设备主键')),
                ('equipment_id', models.CharField(max_length=20, unique=True, verbose_name='设备代码')),
                ('status', models.CharField(choices=[('0', '正常'), ('1', '异常')], default='0', max_length=2, verbose_name='状态')),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='equipment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deviceManage.equipment'),
        ),
    ]
