# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-02-03 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deviceManage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name': '数据', 'verbose_name_plural': '数据'},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': '设备', 'verbose_name_plural': '设备'},
        ),
        migrations.AddField(
            model_name='equipment',
            name='name',
            field=models.CharField(default='设备', max_length=200, verbose_name='设备名称'),
        ),
        migrations.AlterField(
            model_name='data',
            name='equipment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deviceManage.equipment', verbose_name='设备号'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_id',
            field=models.CharField(max_length=200, unique=True, verbose_name='设备代码'),
        ),
    ]
